# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

#use_modular_headers!

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'NSTApp' do
  config = use_native_modules!

  pod 'Firebase/Core', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Analytics', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app', :modular_headers => true
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging', :modular_headers => true
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions', :modular_headers => true
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo', :modular_headers => true
  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview', :modular_headers => true
  # Ajoutez le pod pour la géolocalisation
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation', :modular_headers => true
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
