name: Build iOS

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushes vers la branche main
  pull_request:
    branches:
      - main  # Déclenche le workflow sur les pull requests vers la branche main

jobs:
  build:
    runs-on: macos-latest  # Utilise le dernier runner macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Cloner le dépôt

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Spécifie la version de Node.js que tu utilises
        
    - name: Navigate to project directory
      run: cd Dev/NSTApp
      
    - name: Clean npm cache
      run: npm cache clean --force  # Nettoie le cache npm
      working-directory: Dev/NSTApp

    - name: Install dependencies
      run: npm install  # Installe les dépendances npm
      working-directory: Dev/NSTApp

    - name: Install CocoaPods dependencies
      run: cd ios && pod install --verbose  # Installe les dépendances CocoaPods et ajoute --verbose pour plus de logs
      working-directory: Dev/NSTApp

    - name: List available simulators
      run: xcrun simctl list devices  # Liste les simulateurs disponibles

    - name: Build iOS
      run: |
        xcodebuild clean -workspace ios/NSTApp.xcworkspace -scheme NSTAppScheme  # Nettoie le projet avec le bon workspace et scheme
        xcodebuild build -workspace ios/NSTApp.xcworkspace -scheme NSTAppScheme -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' -verbose  # Lance la build sur un simulateur spécifique et affiche les logs détaillés
      env:
        # Ajoute ici des variables d'environnement nécessaires, comme les clés de signature, MATCH_PASSWORD, etc.
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      working-directory: Dev/NSTApp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # Télécharge les artefacts de la build
      with:
        name: ios-build-artifacts  # Le nom des artefacts que tu veux télécharger
        path: Dev/NSTApp/ios/build/

