name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Navigate to project directory
      run: cd NSTApp

    - name: Clean npm cache
      run: npm cache clean --force
      working-directory: NSTApp

    - name: Install dependencies
      run: npm install
      working-directory: NSTApp

    - name: Update CocoaPods
      run: gem install cocoapods

    - name: Clean CocoaPods installation
      run: |
        rm -rf ios/Pods ios/Podfile.lock
      working-directory: NSTApp/ios

    - name: Update CocoaPods dependencies
      run: pod update --no-repo-update
      working-directory: NSTApp/ios

    - name: Install CocoaPods dependencies
      run: |
        cd ios
        pod install --verbose
      working-directory: NSTApp

    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: ~/.cocoapods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Build iOS
      run: |
        xcodebuild clean -workspace ios/NSTApp.xcworkspace -scheme NSTAppScheme
        xcodebuild build -workspace ios/NSTApp.xcworkspace -scheme NSTAppScheme -sdk iphonesimulator -verbose
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      working-directory: NSTApp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
